In [1]:
# Import the numpy library and check its version.

import numpy as np

print(np.__version__)

2.5.2


Task 2:

Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
Generate an array of 10 evenly spaced values between 0 and 5.

In [2]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])

array_2d = np.arange(1, 10).reshape(3, 3)

array_spaced = np.linspace(0, 5, 10)

print("1D Array:\n", array_1d)
print("\n2D Array:\n", array_2d)
print("\nEvenly Spaced Array:\n", array_spaced)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Evenly Spaced Array:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Task 3:

Access the element in the second row, third column of the 2D array you created above.
Slice the first two rows and the first two columns from the same array.
Modify the value in the last row and first column to 100.

In [3]:
import numpy as np

array_2d = np.arange(1, 10).reshape(3, 3)
element = array_2d[1, 2]
slice_2x2 = array_2d[0:2, 0:2]
array_2d[-1, 0] = 100

print("Accessed Element (Row 2, Col 3):", element)
print("\nFirst 2x2 Slice:\n", slice_2x2)
print("\nModified 2D Array:\n", array_2d)

Accessed Element (Row 2, Col 3): 6

First 2x2 Slice:
 [[1 2]
 [4 5]]

Modified 2D Array:
 [[  1   2   3]
 [  4   5   6]
 [100   8   9]]


Task 4:

Find the shape, size, and data type of the 2D array.
Change the 1D array into a 2D array of shape (5,1).
Flatten a multi-dimensional array back into a 1D array.

In [4]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6], [100, 8, 9]])

shape_2d = array_2d.shape
size_2d = array_2d.size
dtype_2d = array_2d.dtype

array_2d_col = array_1d.reshape(5, 1)

array_flattened = array_2d.flatten()

print("Shape:", shape_2d)
print("Size (total elements):", size_2d)
print("Data Type:", dtype_2d)
print("\nReshaped 1D to (5,1):\n", array_2d_col)
print("\nFlattened Array:\n", array_flattened)

Shape: (3, 3)
Size (total elements): 9
Data Type: int64

Reshaped 1D to (5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]

Flattened Array:
 [  1   2   3   4   5   6 100   8   9]


Task 5:
Add 5 to every element in the 1D array.
Multiply the 2D array by 3.
Perform matrix multiplication between the following two arrays:A = np.array([[1, 2], [3, 4]])B = np.array([[5, 6], [7, 8]])

In [5]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6], [100, 8, 9]])

added_1d = array_1d + 5

scaled_2d = array_2d * 3

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(A, B)  # Or simply: A @ B

print("1D Array + 5:\n", added_1d)
print("\n2D Array * 3:\n", scaled_2d)
print("\nMatrix Product of A and B (A @ B):\n", matrix_product)

1D Array + 5:
 [ 6  7  8  9 10]

2D Array * 3:
 [[  3   6   9]
 [ 12  15  18]
 [300  24  27]]

Matrix Product of A and B (A @ B):
 [[19 22]
 [43 50]]


Task 6:

Create a 3x3 matrix of ones and a 1D array of length 3.
Add the 1D array to each row of the matrix using broadcasting.

In [6]:
import numpy as np

ones_matrix = np.ones((3, 3))
array_1d = np.array([10, 20, 30])

broadcasted_sum = ones_matrix + array_1d

print("3x3 Matrix of Ones:\n", ones_matrix)
print("\n1D Array:\n", array_1d)
print("\nResult after Broadcasting:\n", broadcasted_sum)

3x3 Matrix of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D Array:
 [10 20 30]

Result after Broadcasting:
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]
